demo/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path('', views.index, name='index')
]

proposals/urls.py
from django.conf.urls import url

from proposals.views.cfp import CFPView
from proposals.views.manage import ProposalDeleteView, ProposalListView, ProposalUpdateView
from proposals.views.proposal import ProposalReviewView, ProposalsView, ProposalsInfoView, ProposalsCSVView
from proposals.views.review import ReviewView

urlpatterns = [
    url(r'(?P<pk>\d+)/proposal', ProposalReviewView.as_view(), name='view_reviews'),
    url(r'review_list/$', ProposalsView.as_view(), name="review_list"),
    url(r'proposals_info/$', ProposalsInfoView.as_view(), name="proposals_info"),
    url(r'proposals_info_csv/$', ProposalsCSVView.as_view(), name="proposals_info_csv"),
    url(r'(?P<pk>\d+)/cfp_form', CFPView.as_view()),
    url(r'^$', ProposalListView.as_view(), name='proposal_list'),
    url(r'(?P<pk>\d+)/delete',
        ProposalDeleteView.as_view(),
        name='proposal_delete'
    ),
    url(r'(?P<pk>\d+)/update',
        ProposalUpdateView.as_view(),
        name='proposal_update'
    ),
    url(r'(?P<pk>\d+)/review',
        ReviewView.as_view(),
        name='review_view'
    )
]

pyconlt/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.views.generic.base import TemplateView

from proposals.views.talks import TalksListView

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^talks/', TalksListView.as_view(), name='talks_list'),
    url(r'^', include('presenters.urls')),
    url(r'^proposals/', include('proposals.urls')),
    url(r'^demo/', include('demo.urls')),
    url(r'^', include('program.urls')),
    url(r'^(?P<url>.*/)$', flatpage),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

presenters/models/proposal.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField


PROPOSAL_PENDING = 0
PROPOSAL_ACCEPTED = 1
PROPOSAL_REJECTED = 2

PROPOSAL_STATE = (
    (PROPOSAL_PENDING, _('Pending for approval')),
    (PROPOSAL_ACCEPTED, _('Approved')),
    (PROPOSAL_REJECTED, _('Rejected'))
)

PROPOSAL_TYPE_WORKSHOP = 0
PROPOSAL_TYPE_PRESENTATION = 1

PROPOSAL_TYPE = (
    (PROPOSAL_TYPE_WORKSHOP, _('Workshop')),
    (PROPOSAL_TYPE_PRESENTATION, _('Presentation'))
)


class Proposal(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        help_text=_('Issuer of the proposal'),
        on_delete=models.SET_NULL
    )

    state = models.IntegerField(
        choices=PROPOSAL_STATE,
        default=PROPOSAL_PENDING,
        help_text=_('Current state of proposal')
    )

    type = models.IntegerField(
        choices=PROPOSAL_TYPE,
        help_text=_('Type of proposal')
    )

    duration = models.IntegerField(
        help_text=_('Estimated duration (minutes)')
    )

    short_description = RichTextField(
        help_text=_('Short information about proposal')
    )

    extra_info = RichTextField(
        help_text=_('Extra information'),
        blank=True,
        null=True
    )

    def __repr__(self):
        return '<Proposal type: {0} state: {1} by: {2}>'.format(
                    self.type,
                    self.state,
                    self.user
                )


class Attachment(models.Model):
    proposal = models.ForeignKey(
        Proposal,
        help_text=_('Attachment of proposal'),
        on_delete=models.CASCADE
    )

    upload = models.FileField(
        upload_to='proposal_data/'
    )

proposals/models/attachment.py
import hashlib

from django.db import models
from django.utils.translation import ugettext_lazy as _

from .proposal import Proposal


def unique_dir_path(instance, filename):
    h = hashlib.sha1(str(instance.proposal).encode('UTF-8')).hexdigest()
    return ('proposal_data/{username}/{proposal_hash}/{filename}'.format(
                username=instance.proposal.user.username,
                proposal_hash=h,
                filename=filename
            ))


class Attachment(models.Model):
    proposal = models.ForeignKey(
        Proposal,
        help_text=_('Attachment of proposal'),
        on_delete=models.CASCADE,
        related_name='attachments'
    )

    upload = models.FileField(
        upload_to=unique_dir_path
    )

proposals/models/proposal.py
import bleach
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Avg, TextField
from django.utils.translation import ugettext_lazy as _

from conference.mixins.event_foreign_key import EventFKMixin
from presenters.models import Presenter
from .review import Review


class Proposal(EventFKMixin):

    PROPOSAL_PENDING = 0
    PROPOSAL_ACCEPTED = 1
    PROPOSAL_REJECTED = 2
    PROPOSAL_CANCELLED = 3

    PROPOSAL_STATE = (
        (PROPOSAL_PENDING, _('Pending for approval')),
        (PROPOSAL_ACCEPTED, _('Approved')),
        (PROPOSAL_REJECTED, _('Rejected')),
        (PROPOSAL_CANCELLED, _('Cancelled'))
    )

    PROPOSAL_TYPE_WORKSHOP = 0
    PROPOSAL_TYPE_PRESENTATION = 1

    PROPOSAL_TYPE = (
        (PROPOSAL_TYPE_WORKSHOP, _('Workshop')),
        (PROPOSAL_TYPE_PRESENTATION, _('Presentation'))
    )

    AUDIENCE_JUNIOR = 0
    AUDIENCE_INTERMEDIATE = 1
    AUDIENCE_EXPERT = 2
    AUDIENCE_EXPERIENCE = (
        (AUDIENCE_JUNIOR, _('Junior')),
        (AUDIENCE_INTERMEDIATE, _('Intermediate')),
        (AUDIENCE_EXPERT, _('Expert'))
    )

    user = models.ForeignKey(
        User,
        null=True,
        blank=True,
        help_text=_('Issuer of the proposal'),
        on_delete=models.SET_NULL
    )

    title = models.CharField(
        max_length=1024,
        help_text=_('Title of Proposal'),
    )

    state = models.IntegerField(
        choices=PROPOSAL_STATE,
        default=PROPOSAL_PENDING,
        help_text=_('Current state of proposal')
    )

    type = models.IntegerField(
        choices=PROPOSAL_TYPE,
        help_text=_('Type of proposal')
    )

    duration = models.IntegerField(
        help_text=_('Estimated duration (minutes)')
    )

    short_description = TextField(
        help_text=_('Short information about proposal')
    )

    extra_info = TextField(
        help_text=_('Extra information'),
        blank=True,
        null=True
    )

    audience_experience = models.IntegerField(
        choices=AUDIENCE_EXPERIENCE,
        default=AUDIENCE_JUNIOR,
        help_text=_('Audience level')
    )

    target_audience = TextField(
        help_text=_('Target audience'),
        blank=True,
        null=True
    )

    speaker_grant = models.BooleanField(
        help_text=_('Check if you need a speaker grant'),
        default=False
    )

    grant_description = models.CharField(
        max_length=1024,
        blank=True,
        null=True,
        help_text=_(
            'Short description about travel expenses or expected grant amount')
    )
    # Presenter also links to user, which causes denormalization as this model
    # also has a foreign key to user, but I think that connection to the user
    # should be through a Presenter model because if someone uploads a proposal
    # they become potential presenters and it's ok to have their data. Only
    # they shouldn't be shown then if their presentations are not confirmed.
    presenter = models.ForeignKey(
        Presenter,
        help_text=_('Foreign key to presenter who proposed this '
                    'talk/workshop'),
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    # Proposal or Talk tags ex.: "DevOps, WebDev.."
    tags = ArrayField(
        models.CharField(
            max_length=50,
            blank=True,
            null=True
        ),
        help_text=_("Proposal/Talk tags"),
        blank=True,
        null=True
    )

    def get_review_rating(self):
        rating = Review.objects.filter(
            proposal=self.pk,
            rating__isnull=False
            ).aggregate(Avg('rating')).get('rating__avg', None)

        return format(rating, '.2f') if rating else "No rating"

    def __repr__(self):
        return '<Proposal type: {0} state: {1} by: {2}>'.format(
                    self.type,
                    self.state,
                    self.user
                )

    def __str__(self):
        return self.title or "No title"

proposals/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models.proposal import Proposal
from .models.review import Review


class CFPForm(forms.Form):
    title = forms.CharField(
        label=_('Title'),
        required=True,
    )
    duration = forms.IntegerField(
        label=_('Estimated duration (minutes)'),
        initial=30,
    )

    type = forms.ChoiceField(
        label=_('Type of proposal'),
        choices=Proposal.PROPOSAL_TYPE,
        required=True,
    )

    short_description = forms.CharField(
        label=_('Short description (1000-2000 characters)'),
        required=True,
        widget=forms.Textarea
    )

    audience_experience = forms.ChoiceField(
        label=_('Audience level'),
        choices=Proposal.AUDIENCE_EXPERIENCE,
        required=True,
    )

    target_audience = forms.CharField(
        label=_('Target Audience'),
        required=False,
        widget=forms.Textarea
    )

    extra_info = forms.CharField(
        label=_('Extra info'),
        required=False,
        widget=forms.Textarea
    )

    speaker_grant = forms.BooleanField(
        required=False,
    )

    grant_description = forms.CharField(
        label=_('Grant description'),
        required=False,
    )

    attachment = forms.FileField(
        label=_(
            'Attachments (optional). '
            'Can be anything you would like us to see.'),
        required=False,
    )

    agreement = forms.BooleanField(
        required=True,
    )

    def is_valid(self):
        valid = super(CFPForm, self).is_valid()
        if not valid:
            return False

        data = self.cleaned_data

        if data['speaker_grant'] and not data['grant_description']:
            self._errors['grant_description'] = _(
                'You must provide more information about expected grant'
            )
            return False

        if not data['agreement']:
            self._errors['agreement'] = _(
                    'Code of Conduct needs to be accepted'
            )
            return False

        return True


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ("text", "rating", "status")


class TalksFilterForm(forms.Form):

    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices')
        super().__init__(*args, **kwargs)
        self.fields['option'].choices = choices

    option = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
        required=False)

proposals/views/cfp.py
import logging

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from ..forms import CFPForm
from ..models.attachment import Attachment
from ..models.proposal import Proposal

logger = logging.getLogger(__name__)


class CFPView(View):
    template_name = 'proposals/cfp.html'
    form_class = CFPForm

    @transaction.atomic
    def _save(self, user, form):
        data = form.cleaned_data
        proposal = Proposal(
            user=user,
            title=data['title'],
            type=data['type'],
            duration=data['duration'],
            short_description=data['short_description'],
            extra_info=data['extra_info'],
            audience_experience=data['audience_experience'],
            target_audience=data['target_audience'],
            speaker_grant=data['speaker_grant'],
            grant_description=data['grant_description']
        )
        proposal.save()
        if data['attachment'] is not None:
            attachment = Attachment(
                proposal=proposal,
                upload=data['attachment']
            )
            attachment.save()

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            try:
                self._save(request.user, form)
            except Exception as ex:
                form.add_error(None, _(
                        'Unable to store CFP. '
                        'Please report this to site administrator'
                ))
                logger.exception(ex)
            else:
                return redirect('proposal_list')

        return render(request, self.template_name, {'form': form})

proposals/views/manage.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView

from ..models.proposal import Proposal
from ..security import OwnerRequiredMixin


@method_decorator(login_required, name='dispatch')
class ProposalListView(ListView):
    model = Proposal
    template_name = 'proposals/proposal_list.html'
    context_object_name = 'proposals'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ProposalDeleteView(DeleteView, OwnerRequiredMixin):
    model = Proposal
    success_url = reverse_lazy('proposal_list')


class ProposalUpdateView(OwnerRequiredMixin, UpdateView):
    model = Proposal
    fields = ('title', 'type', 'short_description', 'extra_info',
              'audience_experience', 'target_audience', 'speaker_grant',
              'grant_description')
    template_name_suffix = '_update'
    success_url = reverse_lazy('proposal_list')

proposals/views/review.py
import logging

from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from ..forms import ReviewForm
from ..models.proposal import Proposal
from ..models.review import Review

logger = logging.getLogger(__name__)


class ReviewView(View):
    template = "reviews/review_form.html"
    form_class = ReviewForm

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        if not request.user.has_perm("auth.is_committee_member"):
            return HttpResponseForbidden()

        id = kwargs.get('pk')
        proposal = get_object_or_404(Proposal, id=id)

        # Checking if this user has already made a pending review, if yes then prepopulate the form else blank form.
        review = Review.objects.filter(author=request.user, proposal=proposal.pk, status=0).first()
        if review:
            form = self.form_class(initial=model_to_dict(review))
        else:
            form = self.form_class()

        return render(request, self.template, {'form': form, 'proposal': proposal})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        if not request.user.has_perm("auth.is_committee_member"):
            return HttpResponseForbidden()

        form = self.form_class(request.POST)
        pk = kwargs.get('pk')

        if form.is_valid():
            data = form.cleaned_data
            try:
                review, created = Review.objects.get_or_create(
                    author=request.user,
                    proposal_id=pk,
                )
                # review.proposal = Proposal.objects.get(id=pk)
                review.rating = data["rating"]
                review.text = data["text"]
                review.status = data["status"]
                review.save()
                return redirect('review_list')
            except Exception as ex:
                form.add_error(None, _(
                    'Unable to store Review. '
                    'Please report this to site administrator'
                    ))
                logger.exception(ex)
        else:
            return redirect('review_list')

proposals/templates/proposals/cfp.html
{% extends "pyconlt/base.html" %}
{% load i18n %}
{% load material_form %}
{% load static %}

{% block head_links %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'proposals/css/proposals-form.css' %}">
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        {# Hacks to make form render #}
        $(document).ready(function() {
          $('select').material_select();
        });
    </script>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% form form=form %}
                {% part form.speaker_grant %}
                <div class="checkbox-field col s12 required" id="id_speaker_grant_container">
                    <input class="filled-in " id="id_speaker_grant" name="speaker_grant" type="checkbox" />
                    <label for="id_speaker_grant">
                        {% blocktrans %}
                        Speaker grant
                        {% endblocktrans %}
                    </label>
                </div>
                {% endpart %}
                {% part form.agreement %}
                <div class="checkbox-field col s12 required" id="id_agreement_container">
                    <input class="filled-in " id="id_agreement" name="agreement" type="checkbox" />
                    <label for="id_agreement">
                        {% blocktrans %}
                        I agree with <a href="/2019/coc/">Code of Conduct</a>
                        {% endblocktrans %}
                    </label>
                </div>
                {% endpart %}
            {% endform %}
            <button type="submit" name="_submit" class="btn">{% trans "Submit" %}</button>
        </form>
    {% else %}
        {% trans 'You need to <a href="/accounts/login/">Sign in</a> to submit proposal' %}
    {% endif %}

{% endblock content %}

proposals/templates/proposals/proposal_confirm_delete.html
{% extends 'pyconlt/base.html' %}
{% load i18n %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% blocktrans with object=object %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
        {% endblocktrans %}
        <button type="submit" name="submit" class="btn">{% trans "Confirm" %}</button>
    </form>
{% endblock %}

proposals/templates/proposals/proposal_detail.html
{% extends 'pyconlt/base.html' %}
{% load i18n %}

{% block content %}
    <h4 align="center">{{ proposal.title }}</h4>
    <p>Rating: {{ proposal.get_review_rating }}</p>
    <a href="{% url 'proposal_list' %}" class="btn">Go Back</a>
<!--    <table>
        <thead>
            <tr>
                <th>
                    {% trans "Author" %}
                </th>
                <th>
                    {% trans "Type" %}
                </th>
                <th>
                    {% trans "State" %}
                </th>
                <th>
                    {% trans "Attachments" %}
                </th>
                <th>
                    {% trans "Rating" %}
                </th>
                <th>
                    {% trans "Review" %}
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    {% if proposal.user.first_name and proposal.user.last_name %}
                        {{ proposal.user.first_name }} {{ proposal.user.last_name }}
                    {% else %}
                        Unknown
                    {% endif %}
                </td>
                <td>
                    {{ proposal.get_type_display }}
                </td>
                <td>
                    {{ proposal.get_state_display }}
                </td>
                <td>
                    {% if proposal.attachments.all %}
                        <ul>
                        {% for attachment in proposal.attachments.all %}
                            <li><a href="{{ attachment.upload.url }}">Download files</a></li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>No attachments</p>
                    {% endif %}
                </td>
                <td>
                    {{ proposal.get_review_rating }}
                </td>
                <td>
                    <a href="/proposals/{{ proposal.id }}/review" class="btn">Add review</a>
                </td>
            </tr>
        </tbody>
    </table> -->
    <hr>
    {% if reviews %}
        {% for review in reviews %}
            <p class="review">
                <div class="date"><strong>Date: </strong>{{ review.created_at }}</div>
                <strong>Author: </strong>{{ review.author }}
                <div><strong>Comment: </strong>{{ review.text }}</div>
                <div><strong>Rating: </strong>{{ review.rating }}</div>
                <div><strong>Status of the review: </strong>{{ review.get_status }}</div>
                <hr>
        {% endfor %}
    {% else %}
        <p align="center">No reviews here yet :(</p>
    {% endif %}
{% endblock content %}

proposals/templates/proposals/proposal_list.html
{% extends 'pyconlt/base.html' %}
{% load i18n %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>
                    {% trans "Title" %}
                </th>
                <th>
                    {% trans "Type" %}
                </th>
                <th>
                    {% trans "State" %}
                </th>
                <th>
                    {% trans "Attachments" %}
                </th>
                <th>
                    {% trans "Actions" %}
                </th>
            </tr>
        </thead>
        <tbody>
        {% for proposal in proposals %}
            <tr>
                <td>
                    {{ proposal.title }}
                </td>
                <td>
                    {{ proposal.get_type_display }}
                </td>
                <td>
                    {{ proposal.get_state_display }}
                </td>
                <td>
                    <ul>
                    {% for attachment in proposal.attachments.all %}
                        <li><a href="{{ attachment.upload.url }}">{{ attachment.upload.name }}</a></li>
                    {% endfor %}
                    </ul>
                </td>
                <td>
                    <a title="{% trans "Update" %}" href="{% url 'proposal_update' pk=proposal.id %}">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a title="{% trans "Delete" %}" href="{% url 'proposal_delete' pk=proposal.id %}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">
                {% trans "No proposals yet" %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

proposals/templates/proposals/proposal_update.html
{% extends "pyconlt/base.html" %}
{% load material_form %}
{% load i18n %}
{% load static %}

{% block head_links %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'proposals/css/proposals.css' %}">
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        {# Hacks to make form render #}
        $(document).ready(function() {
          $('select').material_select();
        });
    </script>
{% endblock %}

{% block content %}
    <form method="POST" class="edit-proposal">
        {% csrf_token %}
        {% form form=form %}
        {% endform %}
        <button type="submit" name="_submit" class="btn">{% trans "Save" %}</button>
    </form>
{% endblock content %}

proposals/templates/proposals/proposals_info.html
{% extends 'pyconlt/base.html' %}
{% load i18n %}

{% block content %}
    <h4 align="center">{% trans "List of Proposals" %}</h4>
    <table>
        <thead>
            <tr>
                <th>
                    {% trans "Author" %}
                </th>
                <th>
                    {% trans "Email" %}
                </th>
                <th>
                    {% trans "Title" %}
                </th>
                <th>
                    {% trans "Type" %}
                </th>
                <th>
                    {% trans "Speaker grant" %}
                </th>
                <th>
                    {% trans "Grant description" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% if proposals %}
                {% for proposal in proposals %}
                    <tr>
                        <td>
                            {% if proposal.presenter.name %}
                                {{ proposal.presenter.name }}
                            {% else %}
                                Unknown
                            {% endif %}
                        </td>
                        <td>
                            {{ proposal.presenter.user.email }}
                        </td>
                        <td>
                            {{ proposal.title }}
                        </td>
                        <td>
                            {{ proposal.get_type_display }}
                        </td>
                        <td>
                            {{ proposal.speaker_grant }}
                        </td>
                        <td>
                            {{ proposal.grant_description }}
                        </td>

                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    {% if not proposals %}
        <p align="center">No proposals here yet :(</p>
    {% endif %}
{% endblock content %}

proposals/templates/proposals/proposals_to_review.html
{% extends 'pyconlt/base.html' %}
{% load i18n %}

{% block content %}
    <h4 align="center">{% trans "List of Proposals" %}</h4>
    <table>
        <thead>
            <tr>
                <th>
                    {% trans "Author" %}
                </th>
                <th>
                    {% trans "Title" %}
                </th>
                <th>
                    {% trans "Type" %}
                </th>
                <th>
                    {% trans "State" %}
                </th>
                <th>
                    {% trans "Attachments" %}
                </th>
                <th>
                    {% trans "Rating" %}
                </th>
                <th>
                    {% trans "Actions" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% if proposals %}
                {% for proposal in proposals %}
                    <tr>
                        <td>
                            {% if proposal.presenter.name %}
                                {{ proposal.presenter.name }}
                            {% else %}
                                Unknown
                            {% endif %}
                        </td>
                        <td>
                            {{ proposal.title }}
                        </td>
                        <td>
                            {{ proposal.get_type_display }}
                        </td>
                        <td>
                            {{ proposal.get_state_display }}
                        </td>
                        <td>
                            {% if proposal.attachments.all %}
                                <ul>
                                {% for attachment in proposal.attachments.all %}
                                    <li><a href="{{ attachment.upload.url }}">Download files</a></li>
                                {% endfor %}
                                </ul>
                            {% else %}
                                <p>No attachments</p>
                            {% endif %}
                        </td>
                        <td>
                            {{ proposal.get_review_rating }}
                        </td>
                        <td>
                            <!-- <a href="/proposals/{{ proposal.pk }}/proposal/" class="btn">Review</a> -->
                            <a href="{% url 'review_view' proposal.pk %}" class="btn">Review</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    {% if not proposals %}
        <p align="center">No proposals here yet :(</p>
    {% endif %}
{% endblock content %}